stack: none

# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf input

image: Visual Studio 2022
platform: x64

environment:
  matrix:
    - nodejs_version: 24.18.0
      GYP_MSVS_VERSION: 2022
      CL: /Zc:strictStrings-

install:
  - ps: Install-Product node $env:nodejs_version x64
  - node --version
  - corepack enable
  - corepack yarn --version
  - corepack yarn install --immutable --network-timeout 600000

test_script:
  - corepack yarn verify

build: off

version: "{build}"
